services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: abdellah
      POSTGRES_PASSWORD: abdellah
      POSTGRES_DB: nest
    networks:
      - abdellahnetwork
  test-db:
    image: postgres:13
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: abdellah
      POSTGRES_PASSWORD: abdellah
      POSTGRES_DB: nest
    networks:
      - abdellahnetwork

networks:
  abdellahnetwork:
